language: cpp
compiler:
  - clang
  #- gcc
install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake # For cmake 2.8.9+
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
script:
  - cmake . -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - make -j4
