language: cpp
compiler:
  - gcc
  #- clang
install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake # For cmake 2.8.9+
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa # For Qt5
  - sudo add-apt-repository --yes ppa:boost-latest/ppa # Updated Boost
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test # gcc 4.9
  - sudo apt-get update -yqq
  - sudo apt-get install -yqq cmake qtbase5-dev libboost1.55-dev libboost-date-time1.55-dev libboost-iostreams1.55-dev libasound2-dev g++-4.8
script:
  - cmake . -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - make -j4
