language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: osx
      compiler: gcc # Don't do a gcc build on OSX
cache: apt
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then .travis/setup_linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then .travis/setup_osx.sh ; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then cmake -DCMAKE_PREFIX_PATH=/opt/qt52/lib/cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON . ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug . ; fi
  - cmake -DCMAKE_PREFIX_PATH=/opt/qt52/lib/cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON .
  - make -j4
  # Exclude any tests that are expected to fail.
  - ./bin/pte_tests exclude:Formats/PowerTabOldImport/Directions
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then coveralls --gcov gcov-4.8 --root . --build-root . --exclude CMakeFiles --exclude-pattern ".*_automoc\.cpp" --exclude-pattern ".*\.moc" --exclude-pattern "/usr/.*" --exclude-pattern ".*moc_.*" --exclude-pattern ".*ui_.*" --exclude-pattern ".*qrc_.*" --exclude-pattern ".*_prefix.*" --exclude-pattern ".*_unity.*" --exclude external | grep -vP "^File '.*'$" | grep -vP "^Creating '.*'$" | grep -vP "^Lines executed:.*" | sed '/^$/d' ; fi
