version: 1.0.{build}

environment:
  BOOST_ROOT: C:\Libraries\boost
  matrix:
    - GENERATOR: "Visual Studio 12"
    - GENERATOR: "Visual Studio 12 Win64"

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - cmake -G "%GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -H. -Bbuild
  - cmake --build build --config "%CONFIGURATION%"

test_script:
  - cd build\bin
  - .\pte_tests.exe
