version: 1.0.{build}

os: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  GENERATOR: "Visual Studio 14 Win64"
  QT_DIR: C:\Qt\5.5\msvc2015_64
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0

configuration:
  - Release

matrix:
  fast_finish: true

install:
  - git submodule init
  - git submodule update

before_build:
  - cmd: dir C:\Qt
  - cmd: dir %BOOST_ROOT%
  - cmd: dir %BOOST_LIBRARYDIR%

build_script:
  - cmake -G "%GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DCMAKE_PREFIX_PATH="%QT_DIR%" -H. -Bbuild
  - cmake --build build --config "%CONFIGURATION%"
